language: c

compiler:
  - gcc
before_install:
  - echo "Reached before install Section - cunit packages install"
  - sudo apt-get update
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
  - sudo apt-get -y install valgrind
 
# #Alternative for the above step - Long 
#  - wget http://downloads.sourceforge.net/project/cunit/CUnit/2.1-2/CUnit-2.1-2-src.tar.bz2
#  - tar -xvjpf CUnit-2.1-2-src.tar.bz2
#  - cd CUnit-2.1-2
#  - ./configure --prefix=$TRAVIS_BUILD_DIR
#  - make
#  - make install
#  - export C_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$C_INCLUDE_PATH
#  - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
#  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
#  #Come back to the repo unwarpped folder
#  - cd $TRAVIS_BUILD_DIR/
install:
  - echo  "Reached Install Section"

script:
  - pwd
  - echo "Reached Script Section - Basics "
  #- gcc Basics/hello.c -E # stop with preprocess, actual tool is cpp
  #- gcc Basics/hello.c   -S            # generate assebly code
  #- gcc Basics/hello.s -c -o hello.o   # assemble the code
  #- gcc Basics/hello.o -o h.out        # link, generate executable
  #- gcc Basics/layoutdemo.c -c -o demo.o
  #- gcc Basics/demo.o
  #- gcc Basics/objdump -t demo.o
  - echo "Reached Script Section - Multi File Compile "
  - gcc   	Linkfile_multifile/demofile2.c Linkfile_multifile/file1.c  	Linkfile_multifile/file2.c -o output
  - ./output
  - size output
  - echo "Reached Script Section - cunit_democode"
  - gcc Cunit\ Tests/intial_demo_code_cunit.c -o cunit_democode -lcunit
  - ./cunit_democode
  - size cunit_democode
  - echo "Reached Script Section - Valgrid Analysis/do tryout GDB also"
  - valgrid ./output
