language: c

compiler:
  - gcc
before_install:
  - echo "Reached before install Section - cunit packages install"
  - sudo apt-get update
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
  - sudo apt-get -y install valgrind
 
# #Alternative for the above step - Long 
#  - wget http://downloads.sourceforge.net/project/cunit/CUnit/2.1-2/CUnit-2.1-2-src.tar.bz2
#  - tar -xvjpf CUnit-2.1-2-src.tar.bz2
#  - cd CUnit-2.1-2
#  - ./configure --prefix=$TRAVIS_BUILD_DIR
#  - make
#  - make install
#  - export C_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$C_INCLUDE_PATH
#  - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
#  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
#  #Come back to the repo unwarpped folder
#  - cd $TRAVIS_BUILD_DIR/
install:
  - echo  "Reached Install Section"

script:
  - pwd
  - echo "Reached Script Section"
  # - gcc  Main.c BubbleSortStack.c Detect_UnderVoltage.c Detect_UnderFrequency.c -o output 
  # - gcc  Main.c BubbleSortStack.c BubbleSortHeap.c  -o output 
  # - gcc  Main.c SelectionSortStack.c SelectionSortHeap.c  -o output 
  - gcc -pthread Main.c BinarySearchHeap.c BinarySearchStack.c -o output 
  # -  gcc Main.c OverVoltageFaultDataPointer.c OverVoltageFaultFunctionPointer.c -o output
  # -  gcc Main.c OverVoltageFaultDataPointer.c -o output

  - ./output
  # - size output

  #- echo "Reached unit Section"
  #- gcc  -I CUnit/Headers CUnit/Sources/Framework/*.c CUnit/Sources/Basic/Basic.c Detect_UnderVoltage.c Detect_UnderFrequency.c Run_cunit.c -o Fault_unit_test
  #- ./Fault_unit_test
  #- size Fault_unit_test

  #- gcc  Detect_UnderVoltage.c Detect_UnderFrequency.c OverVoltageFaultDataPointer.c Run_cunit.c -o Fault_unit_test -lcunit
  # - gcc  OverVoltageFaultDataPointer.c Run_cunit.c -o Fault_unit_test -lcunit
  #- ./Fault_unit_test
  #  - size Fault_unit_test
  #- size output
  #- echo "Reached Script Section - cunit_democode"
  #- gcc Cunit\ Tests/intial_demo_code_cunit.c -o cunit_democode -lcunit
  #- ./cunit_democode
  #- size cunit_democode
  #- echo "Reached Script Section - Valgrid Analysis/do tryout GDB also"
  #- valgrid ./output
