language: c

compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
install:
  - echo  "Reached Install Section"

script:
  - echo "Reached  Script Section"
  #- gcc  Main.c BubbleSortStack.c Detect_UnderVoltage.c Detect_UnderFrequency.c -o output 
  #- gcc  Main.c BubbleSortStack.c BubbleSortHeap.c  -o output 
  - gcc Main.c BinarySearchHeap.c BinarySearchStack.c -o output
  #-  gcc Main.c OverVoltageFaultDataPointer.c OverVoltageFaultFunctionPointer.c -o output
#  -  gcc Main.c OverVoltageFaultDataPointer.c -o output
  - ./output
  - size output

   
  #- echo "Reached unit Section"
  #- gcc  -I CUnit/Headers CUnit/Sources/Framework/*.c CUnit/Sources/Basic/Basic.c Detect_UnderVoltage.c Detect_UnderFrequency.c Run_cunit.c -o Fault_unit_test
  #- ./Fault_unit_test
  #- size Fault_unit_test
  
 # - gcc  Detect_UnderVoltage.c Detect_UnderFrequency.c OverVoltageFaultDataPointer.c Run_cunit.c -o Fault_unit_test -lcunit
  #- gcc  OverVoltageFaultDataPointer.c Run_cunit.c -o Fault_unit_test -lcunit
 # - ./Fault_unit_test
#  - size Fault_unit_test
